### ISSUE TITLE
RasPi5/Linux build problem

### ISSUE THREAD

**Issue by KenDickey** [newspeaklanguage/newspeak#128]
Greetings,

I am following instructions 
  https://github.com/newspeaklanguage/newspeak/blob/master/README.md

with ARM64 for X64 in the build script.

All fine until tool/build.sh
"
Exception in turn without resolver
Unhandled exception: 
NotFound: 'CheckedItemApp'
"
[nsbuild.out.txt](https://github.com/user-attachments/files/18054252/nsbuild.out.txt)

I am probably doing something exceedingly dumb.  Can some kind person help me out?
Thanks much,
-KenD    [Ken(dot)Dickey(at)Whidbey(dot)COM]

**Comment by p3anoman** [comment]
Hi Ken
I always remove that line from the build script.
HTH
John

**Comment by KenDickey** [comment]
OK.  "Too many pronouns".  Took "that line" to be 
    RuntimeForHopscotchForHTML CheckedItemApp CheckedItemApp.vfuel \

Builds fine and now able to serve and view `http://localhost:8081/webIDE/`

Into deeper waters!  Thanks much!!

**Comment by KenDickey** [comment]
Builds fine after tools/build.sh updated for "X64" -> "ARM64' [Raspberry Pi Aarch64]
and removed line
"RuntimeForHopscotchForHTML CheckedItemApp CheckedItemApp.vfuel \"
