### ISSUE TITLE
Long strings mess up messages menu

### ISSUE THREAD

**Issue by gbracha** [newspeaklanguage/newspeak#69]
Strings show up in the messages menu of methods (and factories). If the strings are very long, the menu formatting goes out of control.

**Comment by mzimmerm** [comment]
Just one concrete example to duplicate: ObjectPresenter>>#helpText, then click on "find references" button. 

Actual result: popup too wide to see anything useful. Tricky to get out of.

**Comment by gbracha** [comment]
Good to know. That is the wrong place to put in that filtering though. The mirrors shoudl give you the true results, and not be concerned with UI limitations. But the filtering can be moved to the actual menu code.

**Comment by gbracha** [comment]
So I made the change in the right place and it works pretty well. Arguably one should  parse the symbols to see if they are legal selectors and filter on that basis instead; that could be done in the mirror. But this works for now. Once I push out the fix I'll close this issue, and replace it with a more minor one (showing strings rather than just selectors).

**Comment by gbracha** [comment]
So I made the change in the right place and it works pretty well. Arguably one should  parse the symbols to see if they are legal selectors and filter on that basis instead; that could be done in the mirror. But this works for now. Once I push out the fix I'll close this issue, and replace it with a more minor one (showing strings rather than just selectors).
